### ISSUE TITLE
Should we update the snappy version for some arm device?

### ISSUE THREAD

**Issue by PaienNate** [blevesearch/zapx#285]
[HERE](https://github.com/blevesearch/bleve/issues/1665) I find seems it crash by snappy:

```
runtime.throw({0x4de9d4, 0x5})
        runtime/panic.go:1198 +0x54 fp=0x400041d610 sp=0x400041d5e0 pc=0x461d4
runtime.sigpanic()
        runtime/signal_unix.go:742 +0x1e4 fp=0x400041d650 sp=0x400041d610 pc=0x5ddf4
github.com/golang/snappy.encodeBlock({0x4000414001, 0x99, 0x99}, {0x400005e150, 0x69, 0x70})
```

Seems "github.com/golang/snappy v0.0.1" have some bug, and in its release v0.0.3 I find:

```bug fix to encode_arm64.s: some registers overwritten in memmove call```

consider about it don't have update in few days, I use this to instead in my fork: [https://github.com/klauspost/compress/tree/master/s2](https://github.com/klauspost/compress/tree/master/s2) and have test, seems work well.

Should we update the snappy to a new version?

**Comment by abhinavdangeti** [comment]
https://github.com/blevesearch/zapx/pull/286
